repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: check-json
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: detect-aws-credentials
      args: [ --allow-missing-credentials ]
    - id: detect-private-key

  - repo: https://github.com/awslabs/cfn-python-lint
    rev: v1.15.2 # The version of cfn-lint to use
    hooks:
    - id: cfn-python-lint
      files: .template\.yaml$

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '3.2.256'
    hooks:
    - id: checkov
      verbose: true
      args: [--soft-fail]
      files: \.y(a)?ml$

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    - id: detect-secrets
      args: ["--baseline", ".secrets.baseline"]
