name: Daily Smoke Test

on:
  schedule:
    # Every weekday at 5am
    - cron: '0 5 * * 1-5'
  push:

jobs:
  smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2

        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Run Fraud Smoke test against build environment
        env:
          BROWSER: chrome-headless
          ENVIRONMENT: ${{ secrets.TEST_ENVIRONMENT }}
          coreStubUrl: ${{ secrets.CORE_STUB_URL }}
          coreStubUsername: ${{ secrets.CORE_STUB_USERNAME }}
          coreStubPassword: ${{ secrets.CORE_STUB_PASSWORD }}
          orchestratorStubUrl: ${{ secrets.ORCHESTRATOR_STUB_URL }}
        run: cd acceptance-tests && gradle fraudCriSmokeBuild
