name: Daily Smoke Test

on:
  schedule:
    # Every weekday at 5am
    - cron: '0 5 * * 1-5'
  push:

jobs:
  smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2

        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3

      - name: Run Fraud Smoke test against build environment
        env:
          BROWSER: chrome-headless
          ENVIRONMENT: ${{ secrets.TEST_ENVIRONMENT }}
          CUCUMBER_PUBLISH_ENABLED: true
          coreStubUrl: ${{ secrets.CORE_STUB_URL }}
          coreStubUsername: ${{ secrets.CORE_STUB_USERNAME }}
          coreStubPassword: ${{ secrets.CORE_STUB_PASSWORD }}
          orchestratorStubUrl: ${{ secrets.ORCHESTRATOR_STUB_URL }}
        run: cd acceptance-tests && gradle fraudCriSmokeBuild

      - name: Get test results history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: LIME-Cucumber-gh-pages
          path: LIME-Cucumber-gh-pages

      - name: Cucumber HTML Report action
        uses: PavanMudigonda/html-reporter-github-pages@v1.0
        id: test-report
        if: always()
        with:
          test_results: acceptance-tests/target/cucumber-report
          gh_pages: LIME-Cucumber-gh-pages
          results_history: acceptance-tests/results-history

      - name: Publish Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_branch: LIME-Cucumber-gh-pages
           publish_dir: acceptance-tests/results-history
           keep_files: true