name: Daily Smoke Test

on:
  schedule:
    # Every weekday at 5am
    - cron: '0 5 * * 1-5'
  push:

jobs:
  smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2

        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3

      - name: Run Fraud Smoke test against build environment
        env:
          BROWSER: chrome-headless
          ENVIRONMENT: ${{ secrets.TEST_ENVIRONMENT }}
          coreStubUrl: ${{ secrets.CORE_STUB_URL }}
          coreStubUsername: ${{ secrets.CORE_STUB_USERNAME }}
          coreStubPassword: ${{ secrets.CORE_STUB_PASSWORD }}
          orchestratorStubUrl: ${{ secrets.ORCHESTRATOR_STUB_URL }}
        run: cd acceptance-tests && gradle fraudCriSmokeBuild

#      - name: Get Allure history
#        uses: actions/checkout@v2
#        if: always()
#        continue-on-error: true
#        with:
#          ref: LIME-gh-pages
#          path: LIME-gh-pages
#
#      - name: Allure Report action
#        uses: simple-elf/allure-report-action@master
#        if: always()
#        with:
#          allure_results: acceptance-tests/allure-results
#          allure_history: acceptance-tests/allure-history
#          keep_reports: 5
#          gh_pages: LIME-gh-pages
#
#      - name: Deploy report to Github Pages
#        if: always()
#        uses: peaceiris/actions-gh-pages@v2
#        with:
#          deploy_key: ${{ secrets.CS_PA_TOKEN }}
#        env:
#          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          PUBLISH_BRANCH: LIME-gh-pages
#          PUBLISH_DIR: acceptance-tests/allure-history
