# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Gradle Package Test

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: Step 2 - Set up JDK 17
        uses: actions/setup-java@v2

        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Run Fraud Smoke test against build environment
        env:
          BROWSER: chrome-headless
          ENVIRONMENT: ${{ secrets.TEST_ENVIRONMENT }}
          coreStubUrl: ${{ secrets.CORE_STUB_URL }}
          coreStubUsername: ${{ secrets.CORE_STUB_USERNAME }}
          coreStubPassword: ${{ secrets.CORE_STUB_PASSWORD }}
          orchestratorStubUrl: ${{ secrets.orchestratorStubUrl }}
        run: cd acceptance-tests && ./gradlew fraudCriSmokeBuild

