name: Deploy to dev
on:
  push:
    branches:
      - main
  workflow_dispatch: # deploy manually

jobs:
  deploy:
    name: Deploy to dev
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      AWS_REGION: eu-west-2
      STACK_NAME: fraud-cri-pipeline
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          cache-overwrite-existing: true

      - name: Setup SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.FRAUD_DEV_CRI_V1_GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t infrastructure/lambda/template.yaml

      - name: SAM build
        run: |
          mkdir out
          sam build -t infrastructure/lambda/template.yaml -b out

      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action@v3.9
        with:
          artifact-bucket-name: "${{ secrets.FRAUD_DEV_CRI_V1_ARTIFACT_SOURCE_BUCKET_NAME }}"
          signing-profile-name: "${{ secrets.DEV_SIGNING_PROFILE_NAME }}"
          working-directory: ./out
